### ISSUE TITLE
Квадраты не занимают поле!

### ISSUE THREAD

**Issue by geravod** [IlnurHA/RectFight#2]
Я играл в эту прекрасную игру, а я заметил факт того, что цвета игроков не занимают поле игры. То есть например выпало мне 1 5 и я могу  выбрать уже "занятые" поля и игра это позволяет. Желаю успехов  исправлении этой фичи.
![photo_2022-10-11_23-58-33](https://user-images.githubusercontent.com/100628362/195197018-6c48b1d1-850b-4c8b-afb2-4b24421d6567.jpg)
 на 1 фотографии показан первый ход, где нужно было выбрать поле 1 на 1.
![photo_2022-10-11_23-58-38](https://user-images.githubusercontent.com/100628362/195197012-c6a65996-2dce-492c-be74-1ec9149ad1f0.jpg)
на 2 фотографии уже второй ход где нужно было выбрать поле 1 на 2, но при этом я смог выбрать то поле которое уже было "занято".

**Comment by IlnurHA** [comment]
Спасибо за нахождение бага. Эта проблема была исправлена. Приятной игры)
